### ISSUE TITLE
Fix package files in frontend

### ISSUE THREAD

**Issue by lpolt** [Drem-Labs/drem-interface#103]
fix package.json and package-lock.json under D:\DremLabs\Repo\drem-interface\client\drem-interface

when running 'npm -i' or 'npm run dev', and error is thrown. this can by bypassed by adding -f, but this needs to be fixed. @aalaoui12 suggests that this has to do with the wagmi/ethers packages, so start by checking that.

**Comment by axanthus** [comment]
Issue already taken care of.
