### ISSUE TITLE
General project problems

### ISSUE THREAD

**Issue by axanthus** [Drem-Labs/drem-interface#114]
### Priority:
- Hot module reloading/ fast refresh is not working as expected in for modals. Interferes with ui implementation.
  - [x] Task: Investigate issue.
  - [x] Behavior: Modal component doesn't rerender, but child components do if changed.
  - Issue fixed #124 

- We have two tsconfig.json files in the same repo which is causing hundreds of Ts errors and interfering with development.
  - [x] **Solution:** Remove redundant top level tsconfig.json 
 - npm install or any other commands don't work w/o --force. See  
   - [x] Issue #93
-  Discuss Hardhat config and if it's being used.
   - [x] Remove it. #117 
### Lesser Priority but still relevant:
- We have two package.json files in the same repo, which is bad practice. Top level one has not been used in a while.
   - [x] **Solution:** Remove redundant top level package.json
   - [x] Also remove extraneous node_modules
- Discuss if we are all applying prettier formatting in our IDE's
- Learn and discuss best practices of monorepo w/ multiple configs

**Comment by Radilx** [comment]
The NPM install issue is here: https://github.com/Drem-Labs/drem-interface/issues/93

**Comment by Evan-Nishi** [comment]
I'm pretty sure the two tsconfigs and package.json files were from when we initially wanted to have the smart contracts and the app in the same repo, hence one package for all the contract libraries, and one for the UI libraries.  We should probably just install all the dependencies in the root directory instead.

**Comment by Evan-Nishi** [comment]
I also committed a prettierrc a while ago but idk what happened to it.  We do have coding guidelines from a while back though, ask @lpolt for access to the google drive.  I think we should also address the fact that we have both headlessUI and materielUI being used which is super unnecessary and just a lot of bloat and future headache waiting to happen.

**Comment by aalaoui12** [comment]
Just created a PR to address the NPM issue: https://github.com/Drem-Labs/drem-interface/pull/115
