### ISSUE TITLE
Resources Tile Component

### ISSUE THREAD

**Issue by Eric-Hong99** [Drem-Labs/drem-interface#13]
Implement the resources tile component. A resources tile component should include the following:
- Image background
- Bold Main Text
- Type Sub-text
- 'Learn >' Button

DOD: Make a sample tile component with all of the above functionality and with a visual style consistent with the images below. Should be responsive for mobile + web. 

![image](https://user-images.githubusercontent.com/34068439/180914584-ccee42c4-015b-48f9-8bbc-d5345f6fee12.png)
![image](https://user-images.githubusercontent.com/34068439/180914595-7e382c7e-239a-4a08-bb90-1dce040f77fe.png)

**Comment by Evan-Nishi** [comment]
The Learn > button is just a link right?  or should it be a dropdown thing with a preview of the article

**Comment by Eric-Hong99** [comment]
It's a link IIRC

**Comment by Radilx** [comment]
This is added as part of #69
