### ISSUE TITLE
Crypto Stock Graph Component

### ISSUE THREAD

**Issue by Eric-Hong99** [Drem-Labs/drem-interface#18]
Implement the crypto stock graph component. A crypto stock graph component includes the following:

- Crypto Logo Image
- Bold Name Text
- Ticker Sub-text 
- 'Swap' button
- Current Price Text (Bold, big)
- Percent change text
- Data graph visualization
- Buttons for different time period datasets
- Labels + numbers for 'Rank', 'Price', 'Volume', and 'Marketcap'

Personally recommend using d3.js to create a graph within the component with dataset(s) but can be discussed

Input data needs to be discussed; feel free to suggest things/ask to discuss on Discord/in the comments. 

DOD: Make a sample crypto stock graph component that displays relevant information/graph(s) based on which time period button is currently clicked + is visually consistent with the image below. Should be responsive for mobile + web.

![image](https://user-images.githubusercontent.com/34068439/181059772-c0fba7ab-bbcb-40bc-af3b-aff6ee6b5034.png)

**Comment by aalaoui12** [comment]
What timeframe is the percent change calculated on? Is it based on the timeframe selected (eg % change over 1 hour, day, year, etc)?

**Comment by Eric-Hong99** [comment]
@lpolt do you know how the data sources calculate percentage change? If not I can try looking it up myself

**Comment by aalaoui12** [comment]
also, the shade of red used here is lighter than the shade in the color palette in Figma
