### ISSUE TITLE
Reusable Card Component

### ISSUE THREAD

**Issue by Eric-Hong99** [Drem-Labs/drem-interface#43]
Implement the reusable modal component. This component is used for various parts of the front-end that include cards. 

The styling of the parts of the components are present in both the image below + int eh Figma. 

DOD: Make a sample reusable card component that is functionally + visually consistent with the image below. Should be responsive for mobile + web.

![image](https://user-images.githubusercontent.com/34068439/186977172-d977f81c-2c05-4eed-a259-d5a4eae2b032.png)

Before implementing, make sure to:
1) Create a general specs sheets describing
- Inputs the component takes (props, state variables, etc.)
- Any high-level logic the component computes/uses
2) Run it by Eric/Luke/Ali to make sure everyone is on the same page before implementing.

**Comment by jodychui** [comment]
The card component/modal takes in one string parameter: styleclass. The styleclass parameter passes in CSS styling to the modal; in other words, it only affects how the card component/modal looks.
