### ISSUE TITLE
Reusable Button Component

### ISSUE THREAD

**Issue by Eric-Hong99** [Drem-Labs/drem-interface#46]
Implement the reusable modal component. This component is used for various parts of the front-end that have buttons to either submit/edit information or let the user continue with a user flow.

The styling of the parts of the components are present in both the image below + in the Figma.

The component should allow for a flexible background, number of buttons, and text.

---

DOD: Make a sample reusable button component that is functionally + visually consistent with the image below. Should be responsive for mobile + web.

![image](https://user-images.githubusercontent.com/34068439/186978213-6eabbff1-4995-4cad-bfb5-a54649ba5094.png)

<img width="557" alt="image" src="https://user-images.githubusercontent.com/22382740/193900523-75486d5a-feb9-4b07-bcd0-c538193cca4b.png">

<img width="454" alt="image" src="https://user-images.githubusercontent.com/22382740/193900572-044da956-72fe-4977-b57f-ece168bcf607.png">

<img width="240" alt="image" src="https://user-images.githubusercontent.com/22382740/193900604-d9f951ff-2105-4987-be8c-288ede6da368.png">

Before implementing, make sure to:
1) Create a general specs sheets describing
- Inputs the component takes (props, state variables, etc.)
- Any high-level logic the component computes/uses
2) Run it by Eric/Luke/Ali to make sure everyone is on the same page before implementing.

**Comment by Eric-Hong99** [comment]
Might separate this into different types of buttons, or have a general style var argument as an input that determines the specific button's color

**Comment by Radilx** [comment]
Seems like #40 did not land. Re-opening this so that we can make sure we have a reusable button component.

**Comment by Radilx** [comment]
Going to tackle this now. 

N.B. once the change lands in main we will have to go back and modify some of the old components to actually use it. Right now there is no standards and buttons are just being added in-component when needed.

**Comment by Radilx** [comment]
Closing #63
