### ISSUE TITLE
Discover Page 

### ISSUE THREAD

**Issue by Eric-Hong99** [Drem-Labs/drem-interface#82]
![Drem-1png](https://user-images.githubusercontent.com/34068439/205749520-225ad329-24ce-401e-915a-43411c860ac0.png)

**Comment by Radilx** [comment]
Hi, 

I created this issue here a while back: https://github.com/Drem-Labs/drem-interface/issues/69 

Patrick and I completed it a few days ago.

**Comment by Eric-Hong99** [comment]
Gotcha, thanks! I'll delete this issue and look at what else needs to be done/improved upon

**Comment by Radilx** [comment]
Okay, I'll message you on Discord.
